Automated test for widgetset build and use but demo fails through with:
 Loading inherited module
'uk.co.q3c.v7.testapp.widgetset.testAppWidgetset'
      [ERROR] Unable to find
'uk/co/q3c/v7/testapp/widgetset/testAppWidgetset.gwt.xml' on your
classpath; could be a typo, or maybe you forgot to include a classpath
entry for source?
   [ERROR] Line 7: Unexpected exception while processing element
'inherits'
com.google.gwt.core.ext.UnableToCompleteException: (see previous log
entries)